version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
  settings:
    revive:
      rules:
        - name: exported
        - name: package-comments

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dennisklein/brig
